dist: bionic

language: c

before_install:
  - export CFLAGS="-coverage -O0"
  - export LDFLAGS="-coverage"

install:
  - make

script:
  - make check || exit 1
  - gcov -o pkg pkg/*.c

after_success:
  - bash <(curl -s https://codecov.io/bash) -X gcov
